Repository codestates-seb/seb41_main_033, pull requests merged in 2023-01, with the labels that each got.

#12 [FE feat] #7 global style setting
  client/src/App.css
  client/src/style.css
Labels: [FE] 손수빈 🐰

#15 Feat/fe layout
  client/public/index.html
  client/src/App.js
  client/src/components/Header.js
  client/src/components/Nav.js
  client/src/index.css
  client/src/index.js
  client/src/style.css
Labels: [FE] 신나현 👻

#22 [Feat/be-member] 멤버 CRUD 구현
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/entity/Member.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/MemberRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/resources/banner.txt
Labels: [BE] 조대희 🌱

#26 [Feat/fe-navView] Nav 컴포넌트 구현
  client/src/App.js
  client/src/assets/Logo.svg
  client/src/assets/addIcon.svg
  client/src/assets/arrowDown.svg
  client/src/assets/boardIcon.svg
  client/src/assets/closeIcon.svg
  client/src/assets/editIcon.svg
  client/src/assets/gameIcon.svg
  client/src/assets/handshakeIcon.svg
  client/src/assets/heartIcon.svg
  client/src/assets/personIcon.svg
  client/src/assets/settingsIcon.svg
  client/src/assets/sms.svg
  client/src/components/Nav.js
  client/src/style.css
Labels: [FE] 신나현 👻

#28 [feat/fe-quitView] Quit page
  client/src/assets/glummy.svg
  client/src/components/QuitCard.jsx
  client/src/pages/Quit.jsx
Labels: [FE] 손수빈 🐰

#29 Feat/be-global
  server/src/main/java/mainproject33/global/logging/SimpleLoggingAop.java
Labels: [BE] 신대경 🐢

#30 Fix/be-gamedb
  server/src/main/java/mainproject33/domain/gamedb/controller/GameDBController.java
  server/src/main/java/mainproject33/domain/gamedb/repository/GameDBRepository.java
  server/src/main/java/mainproject33/domain/gamedb/service/GameDBService.java
  server/src/main/resources/import.sql
Labels: [BE] 신대경 🐢

#32 [feat/fe-quitView] 회원탈퇴 페이지 디자인 수정
  client/src/components/QuitCard.jsx
Labels: [FE] 손수빈 🐰

#37 [fe/fe-modalView] Modal View
  client/src/components/Popup.jsx
Labels: [FE] 손수빈 🐰

#34 [feat/fe-MatchingWriteView]매칭게시글 작성 view기능
  client/src/App.js
  client/src/components/DropDown.js
  client/src/components/input.js
  client/src/pages/MatchingWrite.js
  client/src/style.css
Labels: [FE] 김소라 ✨

#38 [feat/fe-headerView] Header 컴포넌트 구현
  client/src/App.js
  client/src/assets/defaultImg.svg
  client/src/assets/search.svg
  client/src/components/Header.js
  client/src/style.css
Labels: [FE] 신나현 👻

#39 [FE feat] #35 로그인 페이지지view
  client/src/App.js
  client/src/data/gamelist.js
  client/src/pages/Login.js
Labels: [FE] 김소라 ✨

#42 feat/fe-headerView
  client/src/App.js
  client/src/components/Header.jsx
  client/src/components/Nav.jsx
  client/src/components/SearchBar.jsx
Labels: [FE] 신나현 👻

#45 refactor/be-match
  server/src/main/java/mainproject33/domain/matchboard/dto/MatchBoardDto.java
  server/src/main/java/mainproject33/domain/matchboard/utils/validator/TagsValidator.java
Labels: [BE] 신대경 🐢

#46 [Feat/be security] security 설정 및 jwt 구현
  server/build.gradle
  server/src/main/java/mainproject33/config/CustomFilterConfiguration.java
  server/src/main/java/mainproject33/config/RedisConfiguration.java
  server/src/main/java/mainproject33/config/SecurityConfiguration.java
  server/src/main/java/mainproject33/domain/comment/service/CommentService.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/entity/Member.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/MemberRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/userboard/service/UserBoardService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
  server/src/main/java/mainproject33/global/security/controller/authController.java
  server/src/main/java/mainproject33/global/security/dto/LoginDto.java
  server/src/main/java/mainproject33/global/security/dto/Principal.java
  server/src/main/java/mainproject33/global/security/dto/TokenDto.java
  server/src/main/java/mainproject33/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/mainproject33/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/mainproject33/global/security/handler/CustomAccessDeniedHandler.java
  server/src/main/java/mainproject33/global/security/handler/CustomAuthenticationEntryPoint.java
  server/src/main/java/mainproject33/global/security/jwt/JwtTokenizer.java
  server/src/main/java/mainproject33/global/security/redis/RedisDao.java
  server/src/main/java/mainproject33/global/security/service/AuthService.java
  server/src/main/java/mainproject33/global/security/userdetails/MemberDetailsService.java
  server/src/main/java/mainproject33/global/security/utils/CustomAuthorityUtils.java
  server/src/main/java/mainproject33/global/security/utils/ErrorResponder.java
  server/src/main/java/mainproject33/global/security/utils/HeaderMapRequestWrapper.java
Labels: [BE] 조대희 🌱

#50 [feat/fe-profileView] Profile page & Pagination component
  client/src/assets/arrowBack.svg
  client/src/assets/arrowForward.svg
  client/src/components/Pagination.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/ProfileContent.jsx
  client/src/components/ProfileContentList.jsx
  client/src/components/QuitCard.jsx
  client/src/data/dummyGames.json
  client/src/data/dummyMatchContents.json
  client/src/data/dummyStoryContents.json
  client/src/pages/Profile.jsx
  client/src/style.css
Labels: [FE] 손수빈 🐰

#43 [feat/fe-MatchingView]매칭게시글목록 뷰
  client/src/App.js
  client/src/components/DropDown.jsx
  client/src/components/Header.jsx
  client/src/components/MatchingCard.jsx
  client/src/components/Nav.jsx
  client/src/components/Popup.jsx
  client/src/components/QuitCard.jsx
  client/src/components/SearchBar.jsx
  client/src/components/input.jsx
  client/src/data/gamelist.js
  client/src/pages/Login.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/Quit.jsx
  client/src/util/displayedAt.js
Labels: [FE] 김소라 ✨

#54 [Feat/fe- matching detail view]매칭디테일 화면구현
  client/src/App.js
  client/src/components/MatchDetails.jsx
  client/src/components/MatchingCard.jsx
  client/src/components/Pagination.jsx
  client/src/components/UserCard.jsx
  client/src/pages/MatchingDetail.jsx
Labels: [FE] 김소라 ✨

#52 [feat/fe-storyView] 유저게시글 화면 구현
  client/src/App.js
  client/src/components/StorySingle.jsx
  client/src/components/WriteFloatButton.jsx
  client/src/data/dummyDataStory.js
  client/src/pages/Story.jsx
Labels: [FE] 신나현 👻

#58 refactor/be-match
  server/src/main/java/mainproject33/domain/matchboard/controller/MatchBoardController.java
  server/src/main/java/mainproject33/domain/matchboard/dto/MatchBoardDto.java
  server/src/main/java/mainproject33/domain/matchboard/mapper/MatchBoardMapper.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
Labels: [BE] 신대경 🐢

#68 [Refactor/be member] 멤버 CRUD 개선
  server/src/main/java/mainproject33/config/SecurityConfiguration.java
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/entity/Member.java
  server/src/main/java/mainproject33/domain/member/entity/Profile.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/ProfileRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
  server/src/main/java/mainproject33/global/security/filter/JwtAuthenticationFilter.java
Labels: [BE] 조대희 🌱

#69 Feat/be profileimage
  server/build.gradle
  server/src/main/java/mainproject33/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject33/domain/matchboard/entity/MatchBoard.java
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/entity/Profile.java
  server/src/main/java/mainproject33/domain/member/entity/ProfileImage.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/ProfileImageRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/member/service/ProfileImageService.java
  server/src/main/java/mainproject33/global/exception/ExceptionAdvice.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
  server/src/main/java/mainproject33/global/security/filter/JwtAuthenticationFilter.java
Labels: [BE] 신대경 🐢

#70 [Feat/be follow] 멤버 팔로우 구현
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/entity/Follow.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/FollowRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
Labels: [BE] 조대희 🌱

#62 [feat/fe-profileEditView] Profile Edit page & Post/Patch component
  client/src/App.js
  client/src/components/DropDown.jsx
  client/src/components/PostPatch.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/ProfileContentList.jsx
  client/src/components/input.jsx
  client/src/data/dummyMatchContents.json
  client/src/data/dummyStoryContents.json
  client/src/data/dummyUser.json
  client/src/pages/MatchingWrite.jsx
  client/src/pages/ProfileEdit.jsx
Labels: [FE] 손수빈 🐰

#65 [feat/fe-randomGameView] 랜덤게임
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/drum.mp3
  client/src/assets/game.mp3
  client/src/assets/mohagi.svg
  client/src/components/GameRecommend.jsx
  client/src/components/MatchingCard.jsx
  client/src/components/RandomRolling.jsx
  client/src/data/dummyRandomRolling.json
  client/src/hooks/useAudio.jsx
  client/src/pages/Login.jsx
  client/src/util/Animation.js
  client/src/util/drag.jsx
Labels: [FE] 김소라 ✨

#60 [feat/fe-storyDetailView] 스토리(유저게시글) 상세보기 view 구현
  client/src/App.js
  client/src/assets/heart_sprite.svg
  client/src/components/SingleProfileWrap.jsx
  client/src/components/StoryComment.jsx
  client/src/components/StorySingle.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
Labels: [FE] 신나현 👻

#66 [feat/fe-signupView] 회원가입 View 구현
  client/src/App.js
  client/src/pages/Signup.jsx
  client/src/style.css
Labels: [FE] 신나현 👻

#73 [feat/fe-storyWriteView] 스토리 작성 페이지 view 구현
  client/src/App.js
  client/src/assets/addPhoto.svg
  client/src/pages/StoryWrite.jsx
Labels: [FE] 신나현 👻

#74 [Feat/be member like] 멤버 좋아요 구현
  server/src/main/java/mainproject33/config/SecurityConfiguration.java
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/entity/Likes.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/LikesRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
  server/src/main/java/mainproject33/global/security/dto/LoginDto.java
  server/src/main/resources/application.yml
Labels: [BE] 조대희 🌱

#76 Feat/be-profileimage
  server/build.gradle
  server/src/main/java/mainproject33/config/AwsConfig.java
  server/src/main/java/mainproject33/domain/matchboard/dto/MatchBoardDto.java
  server/src/main/java/mainproject33/domain/matchboard/mapper/MatchBoardMapper.java
  server/src/main/java/mainproject33/domain/member/service/ProfileImageService.java
  server/src/main/java/mainproject33/global/security/jwt/JwtTokenizer.java
Labels: [BE] 신대경 🐢

#77 [BE feat] #1 매치 게시글 CRUD
  server/src/main/java/mainproject33/domain/matchboard/controller/MatchBoardController.java
  server/src/main/java/mainproject33/domain/matchboard/dto/MatchBoardDto.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/member/service/ProfileImageService.java
Labels: [BE] 신대경 🐢

#83 [feat/fe-appRoute] Router connection and rename files
  client/src/App.js
  client/src/components/Confetti.jsx
  client/src/components/Drag.jsx
  client/src/components/InputWrap.jsx
  client/src/pages/GameRecommend.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/util/Animation.js
Labels: [FE] 손수빈 🐰

#94 Feat/be-profileimage
  server/src/main/java/mainproject33/domain/matchboard/controller/MatchBoardController.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/member/service/ProfileImageService.java
  server/src/main/java/mainproject33/global/logging/SimpleLoggingAop.java
  server/src/main/java/mainproject33/global/security/controller/AuthController.java
Labels: [BE] 신대경 🐢

#91 [Feat/fe-signupAPI] 회원가입 API 연결
  client/src/App.js
  client/src/components/Header.jsx
  client/src/components/Nav.jsx
  client/src/pages/Signup.jsx
Labels: [FE] 신나현 👻

#90 [feat/fe-profileAPI] Profile page API
  client/src/components/ProfileCard.jsx
  client/src/components/ProfileContent.jsx
  client/src/components/ProfileContentList.jsx
  client/src/pages/Profile.jsx
Labels: [FE] 손수빈 🐰

#87 [feat/fe-login] 로그인 Api
  client/src/pages/Login.jsx
Labels: [FE] 김소라 ✨

#101 [feat/fe-gameImage] Match game icon with DB
  client/public/images/기타.png
  client/public/images/닌텐도.png
  client/public/images/던전앤파이터.png
  client/public/images/디아블로2.png
  client/public/images/디아블로3.png
  client/public/images/로스트아크.png
  client/public/images/롤.png
  client/public/images/마인크래프트.png
  client/public/images/메이플스토리.png
  client/public/images/발로란트.png
  client/public/images/배틀그라운드.png
  client/public/images/사이퍼즈.png
  client/public/images/서든어택.png
  client/public/images/스팀.png
  client/public/images/어몽어스.png
  client/public/images/오버워치2.png
  client/public/images/이터널리턴.png
  client/public/images/파이널판타지14.png
  client/src/util/matchGame.js
Labels: [FE] 손수빈 🐰

#102 [Feat/fe game recommend]게임추천하기 Api연결
  client/src/components/Drag.jsx
  client/src/pages/GameRecommend.jsx
  client/src/pages/MatchingDetail.jsx
Labels: [FE] 김소라 ✨

#105 [feat/fe-storyEditView] 스토리 수정 view 구현
  client/src/App.js
  client/src/components/StoryInputArea.jsx
  client/src/pages/StoryEdit.jsx
  client/src/pages/StoryWrite.jsx
Labels: [FE] 신나현 👻

#108 [Misc/fe login]간단한 코드수정
  client/src/App.js
  client/src/components/Drag.jsx
  client/src/components/DropDown.jsx
  client/src/components/MatchingCard.jsx
  client/src/pages/Login.jsx
  client/src/pages/MatchingEdit.jsx
Labels: [FE] 김소라 ✨

#110 Feat/be-follow
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/entity/Follow.java
  server/src/main/java/mainproject33/domain/member/entity/MemberLikes.java
  server/src/main/java/mainproject33/domain/member/entity/Profile.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/FollowRepository.java
  server/src/main/java/mainproject33/domain/member/repository/LikesRepository.java
  server/src/main/java/mainproject33/domain/member/repository/MemberLikesRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
  server/src/main/java/mainproject33/global/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/mainproject33/global/security/jwt/JwtTokenizer.java
Labels: [BE] 신대경 🐢

#111 [BE refactor] #57 좋아요 기능 리팩토링
  server/src/main/java/mainproject33/domain/boardfile/service/UserBoardFileService.java
  server/src/main/java/mainproject33/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject33/domain/comment/dto/CommentResponseDto.java
  server/src/main/java/mainproject33/domain/comment/mapper/CommentMapper.java
  server/src/main/java/mainproject33/domain/comment/service/CommentService.java
  server/src/main/java/mainproject33/domain/like/service/LikeService.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/userboard/controller/UserBoardController.java
  server/src/main/java/mainproject33/domain/userboard/dto/UserBoardResponseDto.java
  server/src/main/java/mainproject33/domain/userboard/mapper/UserBoardMapper.java
  server/src/main/java/mainproject33/domain/userboard/service/UserBoardService.java
Labels: [BE] 양건모 :star_struck:

#112 [Feat/be block] 멤버 차단 구현
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/entity/Block.java
  server/src/main/java/mainproject33/domain/member/entity/Follow.java
  server/src/main/java/mainproject33/domain/member/entity/MemberLikes.java
  server/src/main/java/mainproject33/domain/member/entity/Profile.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/BlockRepository.java
  server/src/main/java/mainproject33/domain/member/repository/FollowRepository.java
  server/src/main/java/mainproject33/domain/member/repository/MemberLikesRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
Labels: [BE] 조대희 🌱

#117 [feat/fe-storyWriteAPI] 스토리 작성 API 연결
  client/src/App.js
  client/src/components/StoryInputArea.jsx
  client/src/data/apiUrl.js
  client/src/pages/StoryWrite.jsx
Labels: [FE] 신나현 👻

#119 Feat/fe frefactor
  client/public/images/서든어택.png
  client/public/images/오버워치2.png
  client/src/App.js
  client/src/components/Drag.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/MatchingCard.jsx
  client/src/components/RandomRolling.jsx
  client/src/components/UserCard.jsx
  client/src/pages/Login.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingDetail.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/Signup.jsx
  client/src/style.css
  client/src/util/matchGame.js
Labels: [FE] 김소라 ✨

#126 [BE refactor] 프로필 조회 response 수정
  server/src/main/java/mainproject33/domain/matchboard/repository/MatchBoardRepository.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/userboard/repository/UserBoardRepository.java
  server/src/main/java/mainproject33/domain/userboard/service/UserBoardService.java
Labels: [BE] 조대희 🌱

#130 feat/be-match
  server/src/main/java/mainproject33/domain/matchboard/dto/MatchBoardDto.java
  server/src/main/java/mainproject33/domain/matchboard/mapper/MatchBoardMapper.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/global/validator/nickname/NicknameValidator.java
  server/src/main/java/mainproject33/global/validator/tags/TagsValidator.java
Labels: [BE] 신대경 🐢

#131 [Refactor/be member] 로그인 response 수정, securityExceptionHandler 추가, 프로필 Count 메서드 수정
  server/src/main/java/mainproject33/config/CustomFilterConfiguration.java
  server/src/main/java/mainproject33/domain/member/entity/Profile.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/userboard/repository/UserBoardRepository.java
  server/src/main/java/mainproject33/global/security/advice/JwtExceptionAdvice.java
  server/src/main/java/mainproject33/global/security/controller/AuthController.java
  server/src/main/java/mainproject33/global/security/dto/ResponseDto.java
  server/src/main/java/mainproject33/global/security/filter/JwtExceptionHandlerFilter.java
  server/src/main/java/mainproject33/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/mainproject33/global/security/mapper/LoginMapper.java
  server/src/main/java/mainproject33/global/security/service/AuthService.java
Labels: [BE] 조대희 🌱

#138 [feat/fe-storyAPI] 스토리 목록 API 연결
  client/src/App.js
  client/src/components/SingleProfileWrap.jsx
  client/src/components/StoryInputArea.jsx
  client/src/components/StorySingle.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryWrite.jsx
Labels: [FE] 신나현 👻

#142 [feat/be-logout] 로그아웃 구현
  server/src/main/java/mainproject33/config/RedisConfiguration.java
  server/src/main/java/mainproject33/global/security/controller/AuthController.java
  server/src/main/java/mainproject33/global/security/redis/RedisDao.java
  server/src/main/java/mainproject33/global/security/service/AuthService.java
Labels: [BE] 조대희 🌱

#145 feat/be-matchblock
  server/src/main/java/mainproject33/domain/matchboard/controller/MatchBoardController.java
  server/src/main/java/mainproject33/domain/matchboard/repository/MatchBoardRepository.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
  server/src/main/java/mainproject33/domain/member/repository/BlockRepository.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
Labels: [BE] 신대경 🐢

#147 [Feat/be blocklist] 차단 목록 구현
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/dto/BlockResponseDto.java
  server/src/main/java/mainproject33/domain/member/dto/MemberDto.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/BlockRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/exception/ExceptionMessage.java
Labels: [BE] 조대희 🌱

#148 [Feat/fe match refactor] match페이지 코드수정
  client/src/App.js
  client/src/components/Drag.jsx
  client/src/components/DropDown.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/PostPatch.jsx
  client/src/components/RandomRolling.jsx
  client/src/components/UserCard.jsx
  client/src/index.js
  client/src/pages/Login.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingEdit.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/redux/slice/loginstate.js
  client/src/redux/store.js
Labels: [FE] 김소라 ✨

#144 [Feat/fe login statefull]로그인 상태관리
  client/src/App.js
  client/src/pages/Login.jsx
  client/src/redux/slice/loginstate.js
Labels: [FE] 김소라 ✨

#151 [feat/fe-profileRefactor] Refactor Profile, Profile Edit page
  client/src/components/ProfileContent.jsx
  client/src/components/ProfileContentList.jsx
  client/src/pages/Profile.jsx
  client/src/pages/ProfileEdit.jsx
Labels: [FE] 손수빈 🐰

#150 [feat/fe-storyDetailView2] 스토리 상세보기 view 수정사항 반영
  client/src/App.js
  client/src/components/StoryBtn.jsx
  client/src/components/StoryComment.jsx
  client/src/pages/StoryDetail.jsx
  client/src/style.css
Labels: [FE] 신나현 👻

#153 [feat/fe-profileEditFix] Profile Edit page fix
  client/src/components/PostPatch.jsx
  client/src/pages/ProfileEdit.jsx
Labels: [FE] 손수빈 🐰

#155 [feat/fe-profilesAPI] API related to Profile
  client/src/App.js
  client/src/components/Nav.jsx
  client/src/components/ProfileCard.jsx
  client/src/pages/Profile.jsx
  client/src/pages/ProfileEdit.jsx
Labels: [FE] 손수빈 🐰

#159 [Refactor/be member] 멤버 지속적 개선
  server/.gitignore
  server/src/main/java/mainproject33/domain/member/repository/FollowRepository.java
  server/src/main/java/mainproject33/domain/member/repository/MemberLikesRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/resources/application-staging.yml
Labels: [BE] 조대희 🌱

#161 [Refactor/be member]
  server/src/main/java/mainproject33/domain/matchboard/mapper/MatchBoardMapper.java
  server/src/main/java/mainproject33/domain/member/entity/Profile.java
  server/src/main/java/mainproject33/domain/member/mapper/MemberMapper.java
  server/src/main/java/mainproject33/domain/member/repository/BlockRepository.java
  server/src/main/java/mainproject33/domain/member/repository/FollowRepository.java
  server/src/main/java/mainproject33/domain/member/repository/MemberLikesRepository.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/resources/application-staging.yml
Labels: [BE] 조대희 🌱

#164 [feat/fe-storyDetailAPI] 스토리 상세보기 API 연결(댓글, 유저 프로필 연결 제외)
  client/src/App.js
  client/src/components/StoryComment.jsx
  client/src/components/StoryFileView.jsx
  client/src/components/StoryInputArea.jsx
  client/src/components/StorySingle.jsx
  client/src/data/apiUrl.js
  client/src/pages/Login.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryWrite.jsx
  client/src/style.css
Labels: [FE] 신나현 👻

#168 [feat/feat/searchBar] 검색창기능
  client/src/App.js
  client/src/components/SearchBar.jsx
  client/src/pages/Matching.jsx
  client/src/pages/ProfileEdit.jsx
Labels: [FE] 김소라 ✨

#171 [feat/fe-headerAPI] Header component API
  client/src/App.js
  client/src/components/Header.jsx
  client/src/components/Nav.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/UserCard.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryWrite.jsx
  client/src/redux/slice/loginstate.js
Labels: [FE] 손수빈 🐰

#174 Refactor/be-verification
  server/src/main/java/mainproject33/domain/boardfile/service/UserBoardFileService.java
  server/src/main/java/mainproject33/domain/comment/controller/CommentController.java
  server/src/main/java/mainproject33/domain/comment/service/CommentService.java
  server/src/main/java/mainproject33/domain/gamedb/service/GameDBService.java
  server/src/main/java/mainproject33/domain/like/controller/LikeController.java
  server/src/main/java/mainproject33/domain/like/service/LikeService.java
  server/src/main/java/mainproject33/domain/matchboard/controller/MatchBoardController.java
  server/src/main/java/mainproject33/domain/matchboard/service/MatchBoardService.java
  server/src/main/java/mainproject33/domain/member/controller/MemberController.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/domain/member/service/ProfileImageService.java
  server/src/main/java/mainproject33/domain/userboard/controller/UserBoardController.java
  server/src/main/java/mainproject33/domain/userboard/service/UserBoardService.java
  server/src/main/java/mainproject33/global/service/VerificationService.java
  server/src/main/resources/application-staging.yml
Labels: [BE] 신대경 🐢

#176 [feat/fe-stateFix] Header, Nav state undefined error
  client/src/components/Header.jsx
  client/src/components/Nav.jsx
  client/src/redux/slice/loginstate.js
Labels: [FE] 손수빈 🐰

#177 [BE feat] #25 Global 기능 구현
  server/src/main/java/mainproject33/domain/matchboard/controller/MatchBoardController.java
  server/src/main/java/mainproject33/domain/member/service/MemberService.java
  server/src/main/java/mainproject33/global/logging/SimpleLoggingAop.java
Labels: [BE] 신대경 🐢

#178 [feat/fe-storyEditAPI] 스토리 수정 삭제 API 연결
  client/src/App.js
  client/src/components/Loading.jsx
  client/src/components/StoryBtn.jsx
  client/src/components/StoryInputArea.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryEdit.jsx
  client/src/pages/StoryWrite.jsx
Labels: [FE] 신나현 👻

#179 [FE feat/fe-noSearch]검색결과 없음페이지
  client/src/assets/searchoff.svg
  client/src/components/NoSearch.jsx
  client/src/components/ProfileCard.jsx
  client/src/pages/Matching.jsx
Labels: [FE] 김소라 ✨

#180 [Feat/fe match refactor] 매칭하기페이지네이션 코드수정+검색기능 오류
  client/src/App.js
  client/src/components/Drag.jsx
  client/src/components/DropDown.jsx
  client/src/components/Header.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/MatchPagination.jsx
  client/src/components/MatchingWrite.jsx
  client/src/components/SearchBar.jsx
  client/src/components/UserCard.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingEdit.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/redux/slice/userInfo.js
  client/src/redux/store.js
Labels: [FE] 김소라 ✨

#183 [feat/fe-ProfileAPIs] Profile page other APIs
  client/src/assets/blockUser.svg
  client/src/assets/heartEmptyIcon.svg
  client/src/assets/videoIcon.svg
  client/src/components/Nav.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/ProfileContent.jsx
  client/src/components/ProfileContentList.jsx
  client/src/pages/Profile.jsx
Labels: [FE] 손수빈 🐰

#185 [feat/fe-blockView] Block List page
  client/src/App.js
  client/src/components/BlockUserList.jsx
  client/src/components/PostPatch.jsx
  client/src/pages/BlockList.jsx
  client/src/pages/ProfileEdit.jsx
Labels: [FE] 손수빈 🐰

#186 [feat/fe-quitAPI] Quit page API
  client/src/assets/glummy.svg
  client/src/components/QuitCard.jsx
Labels: [FE] 손수빈 🐰

#188 [feat/fe-storyInfScroll] (지옥의) 스토리 무한스크롤 구현
  client/src/components/Loading.jsx
  client/src/pages/Story.jsx
Labels: [FE] 신나현 👻

#189 [feat/fe-storyComment] 댓글 CRUD 구현, API 연결 (좋아요 기능 제외)
  client/src/components/StoryBtn.jsx
  client/src/components/StoryComment.jsx
  client/src/components/StoryComments.jsx
  client/src/pages/StoryDetail.jsx
Labels: [FE] 신나현 👻

#190 [feat/fe-blockAPI] Block List page API
  client/src/App.js
  client/src/components/BlockUserList.jsx
  client/src/redux/slice/blockSlice.js
  client/src/redux/store.js
Labels: [FE] 손수빈 🐰

#195 [feat/fe-readmeView] Readme page
  client/src/App.js
  client/src/assets/curtainIcon.svg
  client/src/assets/readme.svg
  client/src/components/Nav.jsx
  client/src/pages/Readme.jsx
Labels: [FE] 손수빈 🐰

#193 [feat/fe-userRedux] Refactor user state with redux toolkit
  client/src/components/Header.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/ProfileContent.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/redux/slice/profileSlice.js
  client/src/redux/store.js
Labels: [FE] 손수빈 🐰

#202 [feat/fe-metaOG] Set meta open graph
  client/public/favicon.ico
  client/public/favicons/android-icon-144x144.png
  client/public/favicons/android-icon-192x192.png
  client/public/favicons/android-icon-36x36.png
  client/public/favicons/android-icon-48x48.png
  client/public/favicons/android-icon-72x72.png
  client/public/favicons/android-icon-96x96.png
  client/public/favicons/apple-icon-114x114.png
  client/public/favicons/apple-icon-120x120.png
  client/public/favicons/apple-icon-144x144.png
  client/public/favicons/apple-icon-152x152.png
  client/public/favicons/apple-icon-180x180.png
  client/public/favicons/apple-icon-57x57.png
  client/public/favicons/apple-icon-60x60.png
  client/public/favicons/apple-icon-72x72.png
  client/public/favicons/apple-icon-76x76.png
  client/public/favicons/apple-icon-precomposed.png
  client/public/favicons/apple-icon.png
  client/public/favicons/browserconfig.xml
  client/public/favicons/favicon-16x16.png
  client/public/favicons/favicon-32x32.png
  client/public/favicons/favicon-96x96.png
  client/public/favicons/favicon.ico
  client/public/favicons/manifest.json
  client/public/favicons/ms-icon-144x144.png
  client/public/favicons/ms-icon-150x150.png
  client/public/favicons/ms-icon-310x310.png
  client/public/favicons/ms-icon-70x70.png
  client/public/images/gameto_logo.png
  client/public/images/gameto_og.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
Labels: [FE] 손수빈 🐰

#199 [feat/fe-profilePageRefactor] Refactor Profile pagination
  client/src/components/BlockUserList.jsx
  client/src/components/ProfileContent.jsx
  client/src/components/ProfileContentList.jsx
  client/src/components/ProfilePagination.jsx
  client/src/components/QuitCard.jsx
  client/src/redux/slice/loginstate.js
Labels: [FE] 손수빈 🐰

#196 [feat/fe-refatorAll] #181 경로 설정변경 코드수정
  client/src/App.js
  client/src/components/Confetti.jsx
  client/src/components/Drag.jsx
  client/src/components/Loading.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/Nav.jsx
  client/src/pages/Login.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingDetail.jsx
  client/src/pages/MatchingEdit.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryEdit.jsx
  client/src/pages/StoryWrite.jsx
Labels: [FE] 김소라 ✨

#203 feat/be-security
  server/src/main/java/mainproject33/global/security/jwt/JwtTokenizer.java
Labels: [BE] 신대경 🐢

#206 [feat/fe-storyRefactor] 스토리 리팩토링, 부족한 기능 추가
  client/src/App.js
  client/src/components/Header.jsx
  client/src/components/SearchBar.jsx
  client/src/components/StoryComment.jsx
  client/src/components/StoryComments.jsx
  client/src/index.js
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
Labels: [FE] 신나현 👻

#208 [Feat/fe login token] 리프레시 토큰으로 재발급 처리+작성페이지 유효성 알림창
  client/src/components/Drag.jsx
  client/src/components/Header.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/UserCard.jsx
  client/src/pages/Login.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingDetail.jsx
  client/src/pages/MatchingEdit.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/Readme.jsx
  client/src/redux/slice/loginstate.js
  client/src/util/validity.js
Labels: [FE] 김소라 ✨

#215 [feat/fe-cssRespCheck] CSS 검수 및 반응형 작업
  client/public/index.html
  client/src/App.js
  client/src/assets/logoImgM.svg
  client/src/assets/logoutIcon.svg
  client/src/components/BlockUserList.jsx
  client/src/components/Header.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/MatchingCard.jsx
  client/src/components/Nav.jsx
  client/src/components/PostPatch.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/ProfileContent.jsx
  client/src/components/ProfileContentList.jsx
  client/src/components/QuitCard.jsx
  client/src/components/StoryFileView.jsx
  client/src/components/StorySingle.jsx
  client/src/components/UserCard.jsx
  client/src/components/WriteFloatButton.jsx
  client/src/data/breakpoint.js
  client/src/pages/BlockList.jsx
  client/src/pages/Login.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingDetail.jsx
  client/src/pages/MatchingEdit.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/Profile.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/pages/Signup.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryEdit.jsx
  client/src/pages/StoryWrite.jsx
  client/src/style.css
Labels: [FE] 신나현 👻

#216 [feat/fe-popupContext] Insert Popup
  client/src/App.js
  client/src/components/Header.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/Nav.jsx
  client/src/components/Popup.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/QuitCard.jsx
  client/src/components/StorySingle.jsx
  client/src/pages/Matching.jsx
  client/src/pages/MatchingEdit.jsx
  client/src/pages/MatchingWrite.jsx
  client/src/pages/ProfileEdit.jsx
  client/src/pages/Signup.jsx
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryEdit.jsx
Labels: [FE] 손수빈 🐰

#217 [feat/fe-storyfriend] 친구 스토리 추가, 몇몇 코드 리팩토링
  client/src/assets/arrowHistory.svg
  client/src/components/Header.jsx
  client/src/components/Popup.jsx
  client/src/components/ProfileCard.jsx
  client/src/components/StoryAll.jsx
  client/src/components/StoryFileView.jsx
  client/src/components/StoryFriend.jsx
  client/src/components/StorySingle.jsx
  client/src/data/apiUrl.js
  client/src/pages/Story.jsx
  client/src/pages/StoryDetail.jsx
Labels: [FE] 신나현 👻

#221 [feat/fe-profileStoryFix] Fix Profile page
  client/public/images/던전앤파이터.png
  client/public/images/디아블로2.png
  client/public/images/디아블로3.png
  client/public/images/로스트아크.png
  client/public/images/롤.png
  client/public/images/마인크래프트.png
  client/public/images/메이플스토리.png
  client/public/images/발로란트.png
  client/public/images/배틀그라운드.png
  client/public/images/사이퍼즈.png
  client/public/images/서든어택.png
  client/public/images/스팀.png
  client/public/images/어몽어스.png
  client/public/images/오버워치2.png
  client/public/images/이터널리턴.png
  client/public/images/파이널판타지14.png
  client/src/components/ProfileContentList.jsx
Labels: [FE] 손수빈 🐰

#224 [feat/fe-commentPopupFix] Comment delete Popup
  client/src/components/StoryComment.jsx
  client/src/components/StoryComments.jsx
Labels: [FE] 손수빈 🐰

#229 [fix/fe-storySearchResult] 스토리 검색결과 에러 수정
  client/src/components/Header.jsx
  client/src/components/MatchDetails.jsx
  client/src/components/StoryAll.jsx
Labels: [FE] 신나현 👻

#231 [feat/fe-storyLoadingRefactor] 스토리 작성, 수정시 로딩 UI 삽입
  client/src/components/LoadingFull.jsx
  client/src/pages/StoryDetail.jsx
  client/src/pages/StoryEdit.jsx
  client/src/pages/StoryWrite.jsx
Labels: [FE] 신나현 👻
